export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const ADD_STAFFS = "ADD_STAFFS";
export const DELETE_STAFF = "DELETE_STAFF";
export const EDIT_STAFF = "EDIT_STAFF";
export const ADD_STAFF = "ADD_STAFF";

export const DEPTS_LOADING = "DEPTS_LOADING";
export const DEPTS_FAILED = "DEPTS_FAILED";
export const ADD_DEPTS = "ADD_DEPTS";

export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_FAILED = "SALARY_FAILED";
export const ADD_SALARY = "ADD_SALARY";

export const STAFF_IN_DEPT_LOADING = "STAFF_IN_DEPT_LOADING";
export const STAFF_IN_DEPT_FAILED = "STAFF_IN_DEPT_FAILED";
export const ADD_STAFF_IN_DEPT = "ADD_STAFF_IN_DEPT";
export const CHANGE_DEPT_ID = "CHANGE_DEPT_ID";
